### ISSUE TITLE
Merge to master

### ISSUE THREAD

**Issue by masell** [RobbyB97/yt-iframe-python#2]
You should merge your version branches to master.

**Comment by RobbyB97** [comment]
Thanks, I appreciate the contribution! It's not on the latest version though (made like 5 updates over the course of 2 days). I will test the test then add it to master branch soon.

**Comment by masell** [comment]
uh, rather, all your v.X.X should be in master, so one can make code on latest version.

**Comment by RobbyB97** [comment]
Forgot to mark this as resolved
