### ISSUE TITLE
invalid argument bugs on line 134 for yt.videoResponsive()

### ISSUE THREAD

**Issue by ngjamesng** [RobbyB97/yt-iframe-python#6]
According to the docs, `yt.videoResponsive()` takes in a `URL` and a `layout` argument. 
```python
# code example from https://pypi.org/project/yt-iframe/
url = 'https://www.youtube.com/watch?v=UzIQOQGKeyI' # (Required)
layout = 'singlecolumn' # (Optional)

video = yt.videoResponsive(url, layout=layout) # Get HTML
```

However, when a user is using the library, this TypeError occurs: 
```python
line 134, in getFrames
    frame = videoResponsive(vid, width=width, height=height)
TypeError: videoResponsive() got an unexpected keyword argument 'width'
```

A user brought this up on StackOverflow [here](https://stackoverflow.com/questions/64735463/typeerror-videoresponsive-got-an-unexpected-keyword-argument-width/64736007#64736007).

I'd be happy to take a peek and see if I can fix the bug.

**Comment by RobbyB97** [comment]
Hi, it looks like this can also be resolved by updating the documentation and adding a default value for the width and height arguments. If you want to take a look and add that I'd be happy to merge the PR and update it on PyPI! Other projects are taking all my time up at the moment, so I can't afford to look through it. It also seems like the stylesheet being imported for the responsive layout is a dead link, I will have to update that real quick.

**Comment by RobbyB97** [comment]
Hi @ngjamesng , I actually took some time to update this package. I ensured parameters were being passes between the functions properly in the new version. (https://pypi.org/project/yt-iframe/1.0.5/). Also, I added docstrings to each function to explain clearly what each function does, so I hope you have a better experience with it now!
